// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-secrets.sh from environment variables.
// This file is .gitignored. See BuildSecrets.swift.example for the template.

import Foundation

enum BuildSecrets {
    // MARK: - Supabase

    static let supabaseURL = "http://localhost:8000"
    static let supabaseAnonKey = "your-local-anon-key"

    // MARK: - RevenueCat

    static let revenueCatAPIKey = "appl_REPLACE_WITH_KEY"

    // MARK: - TelemetryDeck

    static let telemetryDeckAppID = ""

    // MARK: - Certificate Pinning

    /// Primary SPKI SHA-256 hash (base64) of your Supabase server's leaf certificate.
    static let certificatePinHash = ""

    /// Backup pin — typically an intermediate CA (e.g., Let's Encrypt ISRG Root X1).
    static let certificateBackupPinHash = "C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M="
}
