#!/bin/bash
# generate-secrets.sh — Generates BuildSecrets.swift from environment variables.
# Used by GitHub Actions during CI/CD. For local dev, copy BuildSecrets.swift.example.
#
# Required environment variables:
#   SUPABASE_URL             — Production Supabase URL
#   SUPABASE_ANON_KEY        — Production Supabase anonymous key
#   REVENUECAT_API_KEY       — RevenueCat Apple API key
#   TELEMETRYDECK_APP_ID     — TelemetryDeck app identifier
#   CERT_PIN_HASH            — Primary certificate pin (SPKI SHA-256, base64)
#   CERT_BACKUP_PIN_HASH     — Backup certificate pin (optional, defaults to Let's Encrypt)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/../Loci/Configuration/BuildSecrets.swift"

# Defaults
CERT_BACKUP="${CERT_BACKUP_PIN_HASH:-C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=}"

cat > "$OUTPUT_FILE" << SWIFT
// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated by scripts/generate-secrets.sh from environment variables.
// This file is .gitignored. See BuildSecrets.swift.example for the template.

import Foundation

enum BuildSecrets {
    // MARK: - Supabase

    static let supabaseURL = "${SUPABASE_URL}"
    static let supabaseAnonKey = "${SUPABASE_ANON_KEY}"

    // MARK: - RevenueCat

    static let revenueCatAPIKey = "${REVENUECAT_API_KEY}"

    // MARK: - TelemetryDeck

    static let telemetryDeckAppID = "${TELEMETRYDECK_APP_ID}"

    // MARK: - Certificate Pinning

    static let certificatePinHash = "${CERT_PIN_HASH}"
    static let certificateBackupPinHash = "${CERT_BACKUP}"
}
SWIFT

echo "BuildSecrets.swift generated at $OUTPUT_FILE"
